USE [master]
GO

/****** Object:  Database [SAOnlineMartDB]    Script Date: 2024/08/30 19:43:53 ******/
CREATE DATABASE [SAOnlineMartDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SAOnlineMartDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SAOnlineMartDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SAOnlineMartDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SAOnlineMartDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SAOnlineMartDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SAOnlineMartDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SAOnlineMartDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SAOnlineMartDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SAOnlineMartDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SAOnlineMartDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [SAOnlineMartDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SAOnlineMartDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SAOnlineMartDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SAOnlineMartDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SAOnlineMartDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SAOnlineMartDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SAOnlineMartDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SAOnlineMartDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SAOnlineMartDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SAOnlineMartDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SAOnlineMartDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SAOnlineMartDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SAOnlineMartDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SAOnlineMartDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SAOnlineMartDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SAOnlineMartDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SAOnlineMartDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SAOnlineMartDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SAOnlineMartDB] SET  MULTI_USER 
GO

ALTER DATABASE [SAOnlineMartDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SAOnlineMartDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SAOnlineMartDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SAOnlineMartDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SAOnlineMartDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SAOnlineMartDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SAOnlineMartDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SAOnlineMartDB] SET  READ_WRITE 
GO

